set updatetime=500

"TODO: set tab stops/expandtab based on language/existing convention for
"codebase/etc.
set softtabstop=4
set expandtab
set shiftwidth=4

filetype plugin on
syntax on

set foldlevelstart=2
set omnifunc=syntaxcomplete#Complete
let g:syntastic_java_javac_config_file_enabled = 1

nnoremap m :make!<CR>

"set spell spelllang=en_us " TODO: enable this without it being a nuisance

set grepprg=grep\ -nH\ $*

set conceallevel=2

let g:tex_flavor = "latex"
let g:tex_conceal = "adgms"

function SetLatexMakePrg()
    if filereadable ("GNUMakefile") || filereadable("Makefile") || filereadable("makefile")
        set makeprg=make
    else
        set makeprg=pdflatex\ -interaction=nonstopmode\ -file-line-error-style\ $*\ %
    endif
endfunction

autocmd FileType tex call SetLatexMakePrg()
autocmd FileType tex set autowrite

let g:rust_fold = 2
