execute pathogen#infect()

set updatetime=500

"TODO: set tab stops/expandtab based on language/existing convention for
"codebase/etc.
set softtabstop=4
set expandtab
set shiftwidth=4
filetype plugin on
syntax on
set omnifunc=syntaxcomplete#Complete
let g:syntastic_java_javac_config_file_enabled = 1

nnoremap m :make<CR>

"set spell spelllang=en_us " TODO: enable this without it being a nuisance

set grepprg=grep\ -nH\ $*

set conceallevel=2

let g:tex_flavor = "latex"
let g:tex_conceal = "adgms"

autocmd FileType tex set makeprg=pdflatex\ -interaction=nonstopmode\ -file-line-error-style\ $*\ %
autocmd FileType tex set autowrite
